"""data pipeline tables — stock master, prices, fundamentals, news, AMT profiles

Revision ID: aa2fc8e8551a
Revises: 0002
Create Date: 2026-05-20 13:00:27.232274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.api.database  # noqa: F401 — required for GUID/JSONB type rendering

# revision identifiers, used by Alembic.
revision: str = 'aa2fc8e8551a'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_market_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('point_of_control', sa.Float(), nullable=False),
    sa.Column('value_area_high', sa.Float(), nullable=False),
    sa.Column('value_area_low', sa.Float(), nullable=False),
    sa.Column('initial_balance_high', sa.Float(), nullable=True),
    sa.Column('initial_balance_low', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=True),
    sa.Column('excess', sa.Boolean(), nullable=True),
    sa.Column('single_prints', src.api.database.JSONB(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('session_range', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('metrics', src.api.database.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'session_date', name='uq_amt_profile')
    )
    op.create_index('idx_amt_profile_type', 'auction_market_profiles', ['profile_type', 'session_date'], unique=False)
    op.create_index('idx_amt_stock_date', 'auction_market_profiles', ['stock_code', 'session_date'], unique=False)
    op.create_index(op.f('ix_auction_market_profiles_session_date'), 'auction_market_profiles', ['session_date'], unique=False)
    op.create_index(op.f('ix_auction_market_profiles_stock_code'), 'auction_market_profiles', ['stock_code'], unique=False)
    op.create_table('daily_stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('turnover_value', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('is_trading_day', sa.Boolean(), nullable=True),
    sa.Column('is_corporate_action', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'date', name='uq_stock_date')
    )
    op.create_index('idx_daily_prices_date_stock', 'daily_stock_prices', ['date', 'stock_code'], unique=False)
    op.create_index('idx_daily_prices_date_volume', 'daily_stock_prices', ['date', 'volume'], unique=False, postgresql_ops={'volume': 'DESC'})
    op.create_index('idx_daily_prices_quality', 'daily_stock_prices', ['data_quality', 'date'], unique=False)
    op.create_index('idx_daily_prices_stock_date_desc', 'daily_stock_prices', ['stock_code', 'date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.create_index(op.f('ix_daily_stock_prices_date'), 'daily_stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_daily_stock_prices_stock_code'), 'daily_stock_prices', ['stock_code'], unique=False)
    op.create_table('data_quality_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_category', sa.String(length=50), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('is_passing', sa.Boolean(), nullable=True),
    sa.Column('stock_code', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_date_category', 'data_quality_metrics', ['metric_date', 'metric_category', 'is_passing'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_is_passing'), 'data_quality_metrics', ['is_passing'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_measured_at'), 'data_quality_metrics', ['measured_at'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_metric_date'), 'data_quality_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_metric_name'), 'data_quality_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_data_quality_metrics_stock_code'), 'data_quality_metrics', ['stock_code'], unique=False)
    op.create_table('data_refresh_logs',
    sa.Column('id', src.api.database.GUID(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('stock_codes', src.api.database.JSONB(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', src.api.database.JSONB(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('validation_errors', src.api.database.JSONB(), nullable=True),
    sa.Column('memory_used_mb', sa.Float(), nullable=True),
    sa.Column('api_calls_made', sa.Integer(), nullable=True),
    sa.Column('api_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_log_job_date', 'data_refresh_logs', ['job_name', 'target_date', 'status'], unique=False)
    op.create_index('idx_refresh_log_status_started', 'data_refresh_logs', ['status', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.create_index(op.f('ix_data_refresh_logs_job_name'), 'data_refresh_logs', ['job_name'], unique=False)
    op.create_index(op.f('ix_data_refresh_logs_started_at'), 'data_refresh_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_data_refresh_logs_status'), 'data_refresh_logs', ['status'], unique=False)
    op.create_index(op.f('ix_data_refresh_logs_target_date'), 'data_refresh_logs', ['target_date'], unique=False)
    op.create_table('fundamental_reports',
    sa.Column('id', src.api.database.GUID(length=36), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('is_parsed', sa.Boolean(), nullable=True),
    sa.Column('parsing_errors', src.api.database.JSONB(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('stock_code', 'report_date', 'report_type', 'source', name='uq_fundamental_report')
    )
    op.create_index('idx_reports_parsed_status', 'fundamental_reports', ['is_parsed', 'report_type'], unique=False)
    op.create_index(op.f('ix_fundamental_reports_is_parsed'), 'fundamental_reports', ['is_parsed'], unique=False)
    op.create_index(op.f('ix_fundamental_reports_report_date'), 'fundamental_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_fundamental_reports_stock_code'), 'fundamental_reports', ['stock_code'], unique=False)
    op.create_table('intraday_stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('turnover_value', sa.Float(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('ingestion_id', src.api.database.GUID(length=36), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'timestamp', 'interval', name='uq_intraday_stock_ts_interval')
    )
    op.create_index('idx_intraday_source_quality', 'intraday_stock_prices', ['data_source', 'quality_score'], unique=False)
    op.create_index('idx_intraday_stock_date', 'intraday_stock_prices', ['session_date', 'stock_code', 'interval'], unique=False)
    op.create_index(op.f('ix_intraday_stock_prices_ingestion_id'), 'intraday_stock_prices', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_intraday_stock_prices_interval'), 'intraday_stock_prices', ['interval'], unique=False)
    op.create_index(op.f('ix_intraday_stock_prices_session_date'), 'intraday_stock_prices', ['session_date'], unique=False)
    op.create_index(op.f('ix_intraday_stock_prices_stock_code'), 'intraday_stock_prices', ['stock_code'], unique=False)
    op.create_index(op.f('ix_intraday_stock_prices_timestamp'), 'intraday_stock_prices', ['timestamp'], unique=False)
    op.create_table('market_news_articles',
    sa.Column('id', src.api.database.GUID(length=36), nullable=False),
    sa.Column('stock_codes', src.api.database.JSONB(), nullable=True),
    sa.Column('sector_tags', src.api.database.JSONB(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('embedding_vector', src.api.database.JSONB(), nullable=True),
    sa.Column('topics', src.api.database.JSONB(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_news_published_at', 'market_news_articles', ['published_at'], unique=False)
    op.create_index('idx_news_sentiment', 'market_news_articles', ['sentiment_label', 'published_at'], unique=False)
    op.create_index('idx_news_stock_codes', 'market_news_articles', ['stock_codes'], unique=False, postgresql_using='gin')
    op.create_index('idx_news_topics', 'market_news_articles', ['topics'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_market_news_articles_fetched_at'), 'market_news_articles', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_market_news_articles_published_at'), 'market_news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_market_news_articles_source'), 'market_news_articles', ['source'], unique=False)
    op.create_index(op.f('ix_market_news_articles_stock_codes'), 'market_news_articles', ['stock_codes'], unique=False)
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('return_on_assets', sa.Float(), nullable=True),
    sa.Column('earnings_per_share', sa.Float(), nullable=True),
    sa.Column('book_value_per_share', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'report_date', 'report_type', name='uq_stock_fundamentals')
    )
    op.create_index('idx_fundamentals_stock_date', 'stock_fundamentals', ['stock_code', 'report_date'], unique=False, postgresql_ops={'report_date': 'DESC'})
    op.create_index(op.f('ix_stock_fundamentals_report_date'), 'stock_fundamentals', ['report_date'], unique=False)
    op.create_index(op.f('ix_stock_fundamentals_stock_code'), 'stock_fundamentals', ['stock_code'], unique=False)
    op.create_table('stock_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('yahoo_symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('market_cap_category', sa.String(length=20), nullable=True),
    sa.Column('is_lq45', sa.Boolean(), nullable=True),
    sa.Column('is_idx30', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('isin_code', sa.String(length=20), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', src.api.database.JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yahoo_symbol')
    )
    op.create_index('idx_stock_master_active_sector', 'stock_master', ['is_active', 'sector'], unique=False)
    op.create_index('idx_stock_master_lq45_active', 'stock_master', ['is_lq45', 'is_active'], unique=False)
    op.create_index(op.f('ix_stock_master_is_active'), 'stock_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_stock_master_is_lq45'), 'stock_master', ['is_lq45'], unique=False)
    op.create_index(op.f('ix_stock_master_sector'), 'stock_master', ['sector'], unique=False)
    op.create_index(op.f('ix_stock_master_stock_code'), 'stock_master', ['stock_code'], unique=True)
    op.alter_column('alerts', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alerts', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('bot_command_log', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_bot_log_command_time', table_name='bot_command_log')
    op.drop_index('idx_bot_log_user_time', table_name='bot_command_log')
    op.alter_column('pending_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('pending_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_pending_trans_code', table_name='pending_transactions', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index('idx_pending_trans_expires', table_name='pending_transactions', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index('idx_pending_trans_user', table_name='pending_transactions')
    op.alter_column('portfolio', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('risk_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('risk_alerts', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('risk_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('signal_generation_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'signals_generated',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('system_metrics', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_auth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_auth_tokens', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_telegram_auth_chat', table_name='telegram_auth_tokens')
    op.drop_index('idx_telegram_auth_token', table_name='telegram_auth_tokens', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('telegram_preferences', 'alert_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'signal_filter',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'notification_hours',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'watchlist',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_telegram_prefs_user', table_name='telegram_preferences')
    op.alter_column('trading_signals', 'risk_adjusted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trading_signals', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trading_signals', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_users_telegram_chat', table_name='users', postgresql_where='(telegram_chat_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_telegram_chat', 'users', ['telegram_chat_id'], unique=False, postgresql_where='(telegram_chat_id IS NOT NULL)')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'trader'::character varying"),
               existing_nullable=False)
    op.alter_column('trading_signals', 'generated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('trading_signals', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('trading_signals', 'risk_adjusted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.create_index('idx_telegram_prefs_user', 'telegram_preferences', ['user_id'], unique=False)
    op.alter_column('telegram_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'Asia/Jakarta'::character varying"),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'id'::character varying"),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'watchlist',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{}'::text[]"),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'notification_hours',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               server_default=sa.text("'{9,10,11,14,15}'::integer[]"),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'signal_filter',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'all'::character varying"),
               existing_nullable=True)
    op.alter_column('telegram_preferences', 'alert_types',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=sa.text("'{high_confidence,risk_breach,large_position}'::text[]"),
               existing_nullable=True)
    op.create_index('idx_telegram_auth_token', 'telegram_auth_tokens', ['token'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('idx_telegram_auth_chat', 'telegram_auth_tokens', ['telegram_chat_id', 'status'], unique=False)
    op.alter_column('telegram_auth_tokens', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('telegram_auth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('system_metrics', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('system_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'signals_generated',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('signal_generation_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('risk_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('risk_alerts', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('risk_alerts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('portfolio', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_index('idx_pending_trans_user', 'pending_transactions', ['user_id', 'status'], unique=False)
    op.create_index('idx_pending_trans_expires', 'pending_transactions', ['expires_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('idx_pending_trans_code', 'pending_transactions', ['confirmation_code'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('pending_transactions', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('pending_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_index('idx_bot_log_user_time', 'bot_command_log', ['user_id', 'executed_at'], unique=False)
    op.create_index('idx_bot_log_command_time', 'bot_command_log', ['command', 'executed_at'], unique=False)
    op.alter_column('bot_command_log', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('alerts', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('alerts', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('alerts', 'priority',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_master_stock_code'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_sector'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_is_lq45'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_is_active'), table_name='stock_master')
    op.drop_index('idx_stock_master_lq45_active', table_name='stock_master')
    op.drop_index('idx_stock_master_active_sector', table_name='stock_master')
    op.drop_table('stock_master')
    op.drop_index(op.f('ix_stock_fundamentals_stock_code'), table_name='stock_fundamentals')
    op.drop_index(op.f('ix_stock_fundamentals_report_date'), table_name='stock_fundamentals')
    op.drop_index('idx_fundamentals_stock_date', table_name='stock_fundamentals', postgresql_ops={'report_date': 'DESC'})
    op.drop_table('stock_fundamentals')
    op.drop_index(op.f('ix_market_news_articles_stock_codes'), table_name='market_news_articles')
    op.drop_index(op.f('ix_market_news_articles_source'), table_name='market_news_articles')
    op.drop_index(op.f('ix_market_news_articles_published_at'), table_name='market_news_articles')
    op.drop_index(op.f('ix_market_news_articles_fetched_at'), table_name='market_news_articles')
    op.drop_index('idx_news_topics', table_name='market_news_articles', postgresql_using='gin')
    op.drop_index('idx_news_stock_codes', table_name='market_news_articles', postgresql_using='gin')
    op.drop_index('idx_news_sentiment', table_name='market_news_articles')
    op.drop_index('idx_news_published_at', table_name='market_news_articles')
    op.drop_table('market_news_articles')
    op.drop_index(op.f('ix_intraday_stock_prices_timestamp'), table_name='intraday_stock_prices')
    op.drop_index(op.f('ix_intraday_stock_prices_stock_code'), table_name='intraday_stock_prices')
    op.drop_index(op.f('ix_intraday_stock_prices_session_date'), table_name='intraday_stock_prices')
    op.drop_index(op.f('ix_intraday_stock_prices_interval'), table_name='intraday_stock_prices')
    op.drop_index(op.f('ix_intraday_stock_prices_ingestion_id'), table_name='intraday_stock_prices')
    op.drop_index('idx_intraday_stock_date', table_name='intraday_stock_prices')
    op.drop_index('idx_intraday_source_quality', table_name='intraday_stock_prices')
    op.drop_table('intraday_stock_prices')
    op.drop_index(op.f('ix_fundamental_reports_stock_code'), table_name='fundamental_reports')
    op.drop_index(op.f('ix_fundamental_reports_report_date'), table_name='fundamental_reports')
    op.drop_index(op.f('ix_fundamental_reports_is_parsed'), table_name='fundamental_reports')
    op.drop_index('idx_reports_parsed_status', table_name='fundamental_reports')
    op.drop_table('fundamental_reports')
    op.drop_index(op.f('ix_data_refresh_logs_target_date'), table_name='data_refresh_logs')
    op.drop_index(op.f('ix_data_refresh_logs_status'), table_name='data_refresh_logs')
    op.drop_index(op.f('ix_data_refresh_logs_started_at'), table_name='data_refresh_logs')
    op.drop_index(op.f('ix_data_refresh_logs_job_name'), table_name='data_refresh_logs')
    op.drop_index('idx_refresh_log_status_started', table_name='data_refresh_logs', postgresql_ops={'started_at': 'DESC'})
    op.drop_index('idx_refresh_log_job_date', table_name='data_refresh_logs')
    op.drop_table('data_refresh_logs')
    op.drop_index(op.f('ix_data_quality_metrics_stock_code'), table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_metric_name'), table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_metric_date'), table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_measured_at'), table_name='data_quality_metrics')
    op.drop_index(op.f('ix_data_quality_metrics_is_passing'), table_name='data_quality_metrics')
    op.drop_index('idx_quality_date_category', table_name='data_quality_metrics')
    op.drop_table('data_quality_metrics')
    op.drop_index(op.f('ix_daily_stock_prices_stock_code'), table_name='daily_stock_prices')
    op.drop_index(op.f('ix_daily_stock_prices_date'), table_name='daily_stock_prices')
    op.drop_index('idx_daily_prices_stock_date_desc', table_name='daily_stock_prices', postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_daily_prices_quality', table_name='daily_stock_prices')
    op.drop_index('idx_daily_prices_date_volume', table_name='daily_stock_prices', postgresql_ops={'volume': 'DESC'})
    op.drop_index('idx_daily_prices_date_stock', table_name='daily_stock_prices')
    op.drop_table('daily_stock_prices')
    op.drop_index(op.f('ix_auction_market_profiles_stock_code'), table_name='auction_market_profiles')
    op.drop_index(op.f('ix_auction_market_profiles_session_date'), table_name='auction_market_profiles')
    op.drop_index('idx_amt_stock_date', table_name='auction_market_profiles')
    op.drop_index('idx_amt_profile_type', table_name='auction_market_profiles')
    op.drop_table('auction_market_profiles')
    # ### end Alembic commands ###
