"""multi_asset_tables

Revision ID: 17cc7773d7c8
Revises: aa2fc8e8551a
Create Date: 2026-05-20 16:16:10.316055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.api.database  # noqa: F401 — registers custom GUID/JSONB types


# revision identifiers, used by Alembic.
revision: str = '17cc7773d7c8'
down_revision: Union[str, None] = 'aa2fc8e8551a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'interval', name='uq_crypto_symbol_ts_interval')
    )
    op.create_index('idx_crypto_retention', 'crypto_prices', ['interval', 'timestamp'], unique=False)
    op.create_index('idx_crypto_symbol_ts', 'crypto_prices', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_crypto_prices_symbol'), 'crypto_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_crypto_prices_timestamp'), 'crypto_prices', ['timestamp'], unique=False)
    op.create_table('forex_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('high_rate', sa.Float(), nullable=True),
    sa.Column('low_rate', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'interval', name='uq_forex_symbol_ts_interval')
    )
    op.create_index('idx_forex_symbol_ts', 'forex_rates', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_forex_rates_symbol'), 'forex_rates', ['symbol'], unique=False)
    op.create_index(op.f('ix_forex_rates_timestamp'), 'forex_rates', ['timestamp'], unique=False)
    op.create_table('gold_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.String(length=5), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'interval', name='uq_gold_ts_interval')
    )
    op.create_index('idx_gold_ts_desc', 'gold_prices', ['timestamp'], unique=False)
    op.create_index(op.f('ix_gold_prices_timestamp'), 'gold_prices', ['timestamp'], unique=False)
    op.drop_index('idx_daily_prices_date_volume', table_name='daily_stock_prices')
    op.create_index('idx_daily_prices_date_volume', 'daily_stock_prices', ['date', 'volume'], unique=False, postgresql_ops={'volume': 'DESC'})
    op.drop_index('idx_daily_prices_stock_date_desc', table_name='daily_stock_prices')
    op.create_index('idx_daily_prices_stock_date_desc', 'daily_stock_prices', ['stock_code', 'date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_refresh_log_status_started', table_name='data_refresh_logs')
    op.create_index('idx_refresh_log_status_started', 'data_refresh_logs', ['status', 'started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})
    op.drop_index('idx_fundamentals_stock_date', table_name='stock_fundamentals')
    op.create_index('idx_fundamentals_stock_date', 'stock_fundamentals', ['stock_code', 'report_date'], unique=False, postgresql_ops={'report_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fundamentals_stock_date', table_name='stock_fundamentals', postgresql_ops={'report_date': 'DESC'})
    op.create_index('idx_fundamentals_stock_date', 'stock_fundamentals', ['stock_code', sa.text('report_date DESC')], unique=False)
    op.drop_index('idx_refresh_log_status_started', table_name='data_refresh_logs', postgresql_ops={'started_at': 'DESC'})
    op.create_index('idx_refresh_log_status_started', 'data_refresh_logs', ['status', sa.text('started_at DESC')], unique=False)
    op.drop_index('idx_daily_prices_stock_date_desc', table_name='daily_stock_prices', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_daily_prices_stock_date_desc', 'daily_stock_prices', ['stock_code', sa.text('date DESC')], unique=False)
    op.drop_index('idx_daily_prices_date_volume', table_name='daily_stock_prices', postgresql_ops={'volume': 'DESC'})
    op.create_index('idx_daily_prices_date_volume', 'daily_stock_prices', ['date', sa.text('volume DESC')], unique=False)
    op.drop_index(op.f('ix_gold_prices_timestamp'), table_name='gold_prices')
    op.drop_index('idx_gold_ts_desc', table_name='gold_prices')
    op.drop_table('gold_prices')
    op.drop_index(op.f('ix_forex_rates_timestamp'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_symbol'), table_name='forex_rates')
    op.drop_index('idx_forex_symbol_ts', table_name='forex_rates')
    op.drop_table('forex_rates')
    op.drop_index(op.f('ix_crypto_prices_timestamp'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_symbol'), table_name='crypto_prices')
    op.drop_index('idx_crypto_symbol_ts', table_name='crypto_prices')
    op.drop_index('idx_crypto_retention', table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
